import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';

export default function TermsOfService() {
  const navigate = useNavigate();

  return (
    <div className="max-w-3xl mx-auto p-6 space-y-6 bg-background text-foreground animate-in fade-in duration-500">
      <Button variant="ghost" onClick={() => navigate(-1)} className="mb-4">
        ← Back
      </Button>
      
      <h1 className="text-3xl font-bold border-b pb-2">Terms of Service</h1>
      <p className="text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
      
      <div className="space-y-4 text-base leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold mt-6 mb-2">1. Terms</h2>
          <p>By accessing and using Expense Tracker, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this app.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-6 mb-2">2. Use License</h2>
          <p>This application is provided "as is". Permission is granted to temporarily download one copy of the materials (information or software) on Expense Tracker for personal, non-commercial transitory viewing only.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-6 mb-2">3. User Data & Google Integration</h2>
          <p>By using this service, you grant Expense Tracker permission to authenticate via your Google Account and interact with your Google Sheets and Google Drive Application Data folder on your behalf. You acknowledge that:</p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>You are responsible for maintaining the security of your Google Account.</li>
            <li>Expense Tracker acts only as a client-side interface to manage your data stored on Google's servers.</li>
            <li>We are not responsible for any data loss, corruption, or accidental deletion of the spreadsheet generated by this app.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-6 mb-2">4. Disclaimer</h2>
          <p>The materials on Expense Tracker are provided on an 'as is' basis. We make no warranties, expressed or implied, and hereby disclaim and negate all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mt-6 mb-2">5. Limitations</h2>
          <p>In no event shall Expense Tracker or its developers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the application.</p>
        </section>
      </div>
    </div>
  );
}
